-- Add migration script here

INSERT INTO location.county(name) VALUES
("NAIROBI"),
 ("MOMBASA"),
 ("KWALE"),
 ("KILIFI"),
  ("TANA RIVER"),
  ("LAMU"),
  ("TAITA TAVETA"),
  ("GARISSA"),
  ("WAJIR"),
  ("MANDERA"),
  ("MARSABIT"),
  ("ISIOLO"),
  ("MERU"),
  ("THARAKA NITHI"),
  ("EMBU"),
  ("KITUI"),
  ("MACHAKOS"),
  ("MAKUENI"),
  ("NYANDARUA"),
  ("MAKUENI"),
  ("NYERI"),
  ("KIRINYAGA"),
  ("MURANG'A"),
  ("KIAMBU"),
  ("TURKANA"),
  ("WEST POKOT"),
  ("SAMBURU"),
  ("TRANS NZOIA"),
  ("UASIN GISHU"),
  ("ELGEYO MARAKWET"),
  ("NANDI"),
  ("BARINGO"),
  ("LAIKIPIA"),
  ("NAKURU"),
  ("NAROK"),
  ("KAJIADO"),
  ("KERICHO"),
  ("BOMET"),
  ("KAKAMEGA"),
  ("VIHIGA"),
  ("BUNGOMA"),
  ("BUSIA"),
  ("SIAYA"),
  ("HOMA BAY"),
  ("MIGORI"),
  ("KISII"),
  ("NYAMIRA");