services:
  # Redis 3 - no external connections allowed
  - type: redis
    name: redis-service
    region: frankfurt
    plan: starter
    ipAllowList: # required - allow external connections from only these CIDR blocks
      - source: 41.212.60.246
        description: mtwapa
  - type: worker
    name: consumer
    region: frankfurt
    env: docker
    dockerfilePath: ./docker/consumer.Dockerfile
    rootDir: ./rust-workspace
    autoDeploy: true
    envVars:
      - key: APP_REDIS__HOST
        fromService:
          name: redis-service
          type: redis
          property: connectionString
      - key: APP_LOCATION__API_KEY
        sync: false
      - key: APP_EMAIL__AUTH_TOKEN
        sync: false
      - key: APP_DATABASE__HOST
        fromDatabase:
          name: prod
          property: host
      - key: APP_DATABASE__PORT
        fromDatabase:
          name: prod
          property: port
      - key: APP_DATABASE__USERNAME
        fromDatabase:
          name: prod
          property: user
      - key: APP_DATABASE__PASSWORD
        fromDatabase:
          name: prod
          property: password
      - key: APP_DATABASE__DATABASE_NAME
        fromDatabase:
          name: prod
          property: database
      - key: APP_DATABASE__REQUIRE_SSL
        value: true
  - type: pserv
    name: tokenizer
    region: frankfurt
    env: docker
    dockerfilePath: ./docker/tokenizer.Dockerfile
    rootDir: ./rust-workspace
    autoDeploy: true
    envVars:
      - key: APP_REDIS__HOST
        fromService:
          name: redis-service
          type: redis
          property: connectionString
      - key: APP_EXTERNAL_APIS_EMAIL
        sync: false
      - key: APP_EXTERNAL_APIS_LOCATION
        sync: false
    buildFilter:
      paths:
      - docker/tokenizer.Dockerfile
      - shared-kernel/**
      - background_workers/tokenizer/**
databases:
  - name: prod
    region: frankfurt
    plan: starter
    databaseName: prod_app
    user: app_user
    ipAllowList:
      - source: 41.212.60.246
        description: mtwapa
    postgresMajorVersion: 15


