services:
  # Redis 3 - no external connections allowed
  - type: redis
    name: redis-service
    region: frankfurt
    plan: starter
    ipAllowList: # required - allow external connections from only these CIDR blocks
      - source: 41.212.60.246
        description: mtwapa
  - type: worker
    name: consumer
    region: frankfurt
    env: docker
    dockerfilePath: ./background_workers/consumer/Dockerfile
    autoDeploy: false
    envVars:
      - fromGroup: redis-key
      - fromGroup: pg-db-keys
      - key: APP_LOCATION__API_KEY
        sync: false
      - key: APP_EMAIL__AUTH_TOKEN
        sync: false
databases:
  - name: prod
    region: frankfurt
    plan: starter
    databaseName: prod_app
    user: app_user
    ipAllowList:
      - source: 41.212.60.246
        description: mtwapa
    postgresMajorVersion: 15


envVarGroups:
  - name: pg-db-keys
    envVars:
    - key: APP_DATABASE__HOST
      fromDatabase:
        name: prod
        property: host
    - key: APP_DATABASE__PORT
      fromDatabase:
        name: prod
        property: port
    - key: APP_DATABASE__USERNAME
      fromDatabase:
        name: prod
        property: user
    - key: APP_DATABASE__PASSWORD
      fromDatabase:
        name: prod
        property: password
    - key: APP_DATABASE__DATABASE_NAME
      fromDatabase:
        name: prod
        property: database
    - key: APP_DATABASE__REQUIRE_SSL
      value: true
  - name: redis-key
    envVars:
      - key: APP_REDIS__HOST
        fromService:
          name: redis-service
          type: redis
          property: connectionString
