services:
  - type: redis
    name: redis-service
    region: frankfurt
    plan: starter
    ipAllowList: # required - allow external connections from only these CIDR blocks
      - source: 41.212.60.246
        description: mtwapa
  - type: worker
    name: consumer
    region: frankfurt
    env: rust
    buildCommand: cargo build --release --bin consumer
    startCommand: cargo run --release --bin consumer
    rootDir: ./rust-workspace
    autoDeploy: true
    envVars:
      - key: APP_REDIS__HOST
        fromService:
          name: redis-service
          type: redis
          property: connectionString
      - key: APP_LOCATION__API_KEY
        sync: false
      - key: APP_EMAIL__AUTH_TOKEN
        sync: false
      - key: APP_DATABASE__HOST
        fromDatabase:
          name: prod
          property: host
      - key: APP_DATABASE__PORT
        fromDatabase:
          name: prod
          property: port
      - key: APP_DATABASE__USERNAME
        fromDatabase:
          name: prod
          property: user
      - key: APP_DATABASE__PASSWORD
        fromDatabase:
          name: prod
          property: password
      - key: APP_DATABASE__DATABASE_NAME
        fromDatabase:
          name: prod
          property: database
      - key: APP_DATABASE__REQUIRE_SSL
        value: true
  - type: worker
    name: tokenizer
    region: frankfurt
    env: rust
    buildCommand: cargo build --release --bin tokenizer
    startCommand: cargo run --release --bin tokenizer
    rootDir: ./rust-workspace
    autoDeploy: true
    envVars:
      - key: APP_REDIS__HOST
        fromService:
          name: redis-service
          type: redis
          property: connectionString
      - key: APP_EXTERNAL_API_RATE_LIMITS_EMAIL
        sync: false
      - key: APP_EXTERNAL_API_RATE_LIMITS_LOCATION
        sync: false
    buildFilter:
      paths:
      - shared-kernel/**
      - background_workers/tokenizer/**
      - configuration/**

  - type: cron
    name: importer
    region: frankfurt
    env: rust
    buildCommand: cargo build --release --bin importer
    startCommand: cargo run --release --bin importer
    rootDir: ./rust-workspace
    schedule: "0 2 * * *"
    autoDeploy: true
    envVars:
      - key: APP_REDIS__HOST
        fromService:
          name: redis-service
          type: redis
          property: connectionString
      - key: APP_LOCATION__API_KEY
        sync: false
      - key: APP_EMAIL__AUTH_TOKEN
        sync: false
      - key: APP_EMAIL__ADMIN_EMAIL
        sync: false
      - key: APP_DATABASE__HOST
        fromDatabase:
          name: prod
          property: host
      - key: APP_DATABASE__PORT
        fromDatabase:
          name: prod
          property: port
      - key: APP_DATABASE__USERNAME
        fromDatabase:
          name: prod
          property: user
      - key: APP_DATABASE__PASSWORD
        fromDatabase:
          name: prod
          property: password
      - key: APP_DATABASE__DATABASE_NAME
        fromDatabase:
          name: prod
          property: database
      - key: APP_DATABASE__REQUIRE_SSL
        value: true

  - type: web
    name: kplc-alerts-api
    region: frankfurt
    env: rust
    buildCommand: cargo build --release --bin http_server
    startCommand: cargo run --release --bin http_server
    rootDir: ./rust-workspace
    autoDeploy: true
    envVars:
      - key: APP_REDIS__HOST
        fromService:
          name: redis-service
          type: redis
          property: connectionString
      - key: APP_LOCATION__API_KEY
        sync: false
      - key: APP_EMAIL__AUTH_TOKEN
        sync: false
      - key: APP_AUTH__JWKS
        sync: false
      - key: APP_AUTH__AUTHORITIES
        sync: false
      - key: APP_AUTH__AUDIENCES
        sync: false
      - key: APP_DATABASE__HOST
        fromDatabase:
          name: prod
          property: host
      - key: APP_DATABASE__PORT
        fromDatabase:
          name: prod
          property: port
      - key: APP_DATABASE__USERNAME
        fromDatabase:
          name: prod
          property: user
      - key: APP_DATABASE__PASSWORD
        fromDatabase:
          name: prod
          property: password
      - key: APP_DATABASE__DATABASE_NAME
        fromDatabase:
          name: prod
          property: database
      - key: APP_DATABASE__REQUIRE_SSL
        value: true

  - type: web
    name: kplc-alerts
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    rootDir: ./frontend-workspace/blackouts-frontend
    autoDeploy: true
    envVars:
      - key: VITE_API_URL
        sync: false
      - key: VITE_AUTH_DOMAIN
        sync: false
      - key: VITE_AUTH_CLIENT_ID
        sync: false
      - key: VITE_AUTH_AUDIENCE
        sync: false

  - type: worker
    name: migrations
    region: frankfurt
    env: rust
    buildCommand: cargo build --release --bin migrations
    startCommand: cargo run --release --bin migrations
    rootDir: ./rust-workspace
    autoDeploy: true
    envVars:
      - key: APP_DATABASE__HOST
        fromDatabase:
          name: prod
          property: host
      - key: APP_DATABASE__PORT
        fromDatabase:
          name: prod
          property: port
      - key: APP_DATABASE__USERNAME
        fromDatabase:
          name: prod
          property: user
      - key: APP_DATABASE__PASSWORD
        fromDatabase:
          name: prod
          property: password
      - key: APP_DATABASE__DATABASE_NAME
        fromDatabase:
          name: prod
          property: database
      - key: APP_DATABASE__REQUIRE_SSL
        value: true

databases:
  - name: prod
    region: frankfurt
    plan: starter
    databaseName: prod_app
    user: app_user
    ipAllowList:
      - source: 41.212.60.246
        description: mtwapa
      - source: 102.222.223.152
        description: garden city home office
    postgresMajorVersion: 15


