database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "postgres"
  database_name: "blackout"
  require_ssl: false
location_searcher:
  host: "https://maps.googleapis.com/maps/api/place/queryautocomplete/json"
  api_key: ""
