[workspace]
members = [
    "use_cases",
    "storage/*",
    "import_power_interruptions/*",
    "notification_strategies/*",
    "http_server",
    "entities",
    "location_searcher",
    "shared_kernel"
]
