[workspace]
members = [
    "use_cases",
    "storage/*",
    "import_power_interruptions/*",
    "http_server",
    "entities",
    "shared_kernel",
    "background_workers/*",
    "location_subscription",
    "notifications"
]

[profile.dev.package.sqlx-macros]
opt-level = 3