name: Rust

on:
  push:
    branches: ["development"]
  pull_request:
    branches: ["development"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        working-directory: ./rust-workspace
        run: cargo build --verbose
      - name: Run tests
        working-directory: ./rust-workspace
        run: cargo test --verbose
