name: Rust

on:
  push:
    branches: ["development"]
  pull_request:
    branches: ["development"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test-job:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: kplc_alerts
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Build
        working-directory: ./rust-workspace
        run: cargo build --verbose
      - name: Run tests
        working-directory: ./rust-workspace
        run: cargo test --verbose
        env:
          # The hostname used to communicate with the PostgreSQL service container
          APP_DATABASE__HOST: localhost
          # The default PostgreSQL port
          APP_DATABASE__PORT: 5432
          APP_DATABASE__USERNAME: postgres
          APP_DATABASE__PASSWORD: postgres
          APP_DATABASE__DATABASE_NAME: kplc_alerts
