name: Rust

on:
  push:
    branches: ["development"]
  pull_request:
    branches: ["development"]

env:
  CARGO_TERM_COLOR: always

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: node:10.18-jessie

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        working-directory: ./rust-workspace
        run: cargo build --verbose
      - name: Run tests
        working-directory: ./rust-workspace
        run: cargo test --verbose
        env:
          # The hostname used to communicate with the PostgreSQL service container
          APP_DATABASE__HOST: postgres
          # The default PostgreSQL port
          APP_DATABASE__PORT: 5432
          APP_DATABASE__USERNAME: postgres
          APP_DATABASE__PASSWORD: postgres
